name: Docker Push

on:
  release:
    types: [published]

jobs:
    push:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                tag: [
                    1.16-alpine,
                    1.16-alpine-v2,
                    1.17-alpine,
                    1.17-alpine-v2,
                    1.17-alpine-v3,
                    1.17-alpine-v4,
                    1.18-alpine,
                    1.19-alpine,
                    1.20-alpine,
                    1.21-alpine,
                    1.22-alpine,
                    1.23-alpine,
                    1.24-alpine,
                    1.25-alpine,
                    1.26-alpine,
                    1.27-alpine,
                ]

        name: TAG-${{ matrix.tag }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                run: bash build.sh ${{ matrix.tag }}

            -   name: Push Docker Image
                run: bash push.sh ${{ matrix.tag }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'